---
title: "EDA buscas"
output: html_notebook
---

O objeto principal da análise são as buscas e a navegação depois da busca. Criamos esses dados a partir dos dados originais da wikimedia em `/data/search_data.csv`. 

Aqui, exploramos esses dados. 

```{r setup}
library(tidyverse)
library(here)
library(lubridate)
theme_set(theme_bw())
```

```{r ETL}
buscas = read_csv(here::here("data/search_data.csv"))
```
```{r}
glimpse(buscas)
```

```{r}
buscas %>% 
    ggplot(aes(x = session_start_date, y = num_clicks)) +
    geom_point(alpha = .3)
```


```{r}
session_id_clicks <- buscas %>% 
    mutate(day_date = floor_date(session_start_date, unit = "day")) %>%
    #filter(day_date != date("2016-03-08")) %>%
    group_by(session_id, day_date, group) %>%
    summarise(nclicks = sum(num_clicks), nsessions = n())
#    glimpse(session_id_clicks)

session_id_clicks2 <- session_id_clicks %>%
    group_by(day_date, group) %>%
    summarise(zero_clicks = sum(nclicks == 0))
glimpse(session_id_clicks2)
```

```{r}
session_id_clicks2 %>% 
    #filter(day_date != date("2016-03-08")) %>%
    ggplot(aes(x = day_date, y = zero_clicks, color = group)) + 
    geom_point() + geom_line()
```

```{r}
session_id_clicks %>%
    group_by(day_date, group) %>%
    mutate(ctr = sum(nclicks) / sum(nsessions)) %>%
    ggplot() +
    geom_col(aes(x = day_date, y = ctr, fill = group), position = "dodge")
```


```{r}
zeros = buscas %>% select(results, group, session_start_date) %>% mutate(day_date = date(session_start_date))

zeros_per_week =  zeros %>%  group_by(day_date, group) %>% 
    summarise(zeros_results_day = sum(results == 0), total_results = n()) %>%  mutate(proportion = (zeros_results_day/total_results) * 100)

glimpse(zeros_per_week)
```

```{r}
zeros_per_week %>% distinct(day_date)
```

```{r}
zeros_per_week %>% filter(group == "a") %>%
    ggplot(aes(x = day_date, y = total_results)) + 
    geom_col(mapping = aes(fill = "Total de buscas")) + 
    geom_text(aes(label = total_results, y = total_results), size = 3, hjust = 5) +
    geom_col(data = zeros_per_week, mapping = aes(y = zeros_results_day, fill = "Zero resultados")) +      
    geom_text(aes(label = zeros_results_day, y = zeros_results_day), size = 3) +
    scale_x_date(date_labels = "%d-%b-%Y", breaks = zeros_per_week$day_date) +
    coord_flip() +
    labs(
        title = "Grupo 'A'",
        x = "Dia",
        y = "Zero resultados / Total de resultados",
        fill = "Legenda"
    ) + theme(plot.title = element_text(hjust = 0.5))
```

```{r}
zeros_per_week %>% filter(group == "b") %>%
    ggplot(aes(x = day_date, y = total_results)) + 
    geom_col(mapping = aes(fill = "Total de buscas")) + 
    geom_text(aes(label = total_results, y = total_results), size = 3, hjust = 4) +
    geom_col(data = zeros_per_week, mapping = aes(y = zeros_results_day, fill = "Zero resultados")) +      
    geom_text(aes(label = zeros_results_day, y = zeros_results_day), size = 3) +
    scale_x_date(date_labels = "%d-%b-%Y", breaks = zeros_per_week$day_date) +
    coord_flip() +
    labs(
        title = "Grupo 'B'",
        x = "Dia",
        y = "Zero resultados / Total de resultados",
        fill = "Legenda"
    ) + theme(plot.title = element_text(hjust = 0.5))
```

```{r}
zeros_per_week %>%  
    ggplot(aes(x = day_date, y = proportion, color = group)) + 
    geom_point() + geom_line() + labs (
        x = "Dia",
        y = "Zero resultados / Total de resultados (%)",
        color = "Grupo"
    )
```

