---
title: "Ics-hip"
author: "Nailson"
date: "5 de junho de 2019"
output:
  html_document:
    df_print: paged
---

```{r setup}
library(tidyverse)
library(here)
library(lubridate)
library(boot)
library(broom)
theme_set(theme_bw())
```

```{r ETL}
buscas = read_csv(here::here("data/search_data.csv"))
```

```{r}
# buscas = buscas %>% 
#     group_by(session_id, group) %>%
#     summarise(nclicks = sum(num_clicks), nsessions = n())

buscas_ic = buscas %>% 
    mutate(day_date = floor_date(session_start_date, unit = "day")) %>%
    group_by(session_id, day_date, group) %>%
    summarise(nclicks = sum(num_clicks), nsessions = n()) %>%
    ungroup()

#buscas_ic = buscas_ic %>%
#    group_by(day_date, group) #%>%
    # mutate(ctr = sum(nclicks) / sum(nsessions))

glimpse(buscas_ic)
```

## Com ICs

```{r}
theta_diferenca_ab = function(d, i){
    ctrs = d %>% 
        slice(i) %>% 
        group_by(group) %>% 
        summarise(ctr = sum(nclicks) / sum(nsessions)) 
    
    ga = ctrs %>% filter(group == "a") %>% pull(ctr)
    gb = ctrs %>% filter(group == "b") %>% pull(ctr)
    
    ga - gb
}


theta_c_ab = theta_diferenca_ab(buscas_ic, 1:NROW(buscas_ic))

theta_c_ab
```


```{r}
buscas_ic %>% 
    boot(statistic = theta_diferenca_ab, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```

## Com teste de hipótese

```{r}
buscas_hp = buscas %>% 
    mutate(day_date = floor_date(session_start_date, unit = "day")) %>%
    group_by(session_id, day_date, group) %>%
    summarise(nclicks = sum(num_clicks), nsessions = n()) %>%
    ungroup()

glimpse(buscas_hp)
```


```{r}
theta_embaralhado = function(d){
    clickt_rate = d %>%
        mutate(grupo_embaralhado = sample(group, n())) %>%
        group_by(grupo_embaralhado) %>%
        summarise(ctr = sum(nclicks) / sum(nsessions))

    ga = clickt_rate %>% filter(grupo_embaralhado == "a") %>% pull(ctr)
    gb = clickt_rate %>% filter(grupo_embaralhado == "b") %>% pull(ctr)

    ga - gb
}

theta_embaralhado(buscas_hp)
```

```{r}
diffs = replicate(5000, {theta_embaralhado(buscas_hp)})
mean(abs(diffs) >= abs(theta_diferenca_ab(buscas_hp, 1:NROW(buscas_hp))))
```